Repository ariel-os/ariel-os, pull requests merged in 2024-08, with the labels that each got.

#376 chore: inherit workspace lints in every crate
  examples/benchmark/Cargo.toml
  examples/coap/Cargo.toml
  examples/core-sizes/Cargo.toml
  examples/embassy-http-server/Cargo.toml
  examples/embassy-net-tcp/Cargo.toml
  examples/embassy-net-udp/Cargo.toml
  examples/embassy-usb-keyboard/Cargo.toml
  examples/embassy/Cargo.toml
  examples/hello-world-async/Cargo.toml
  examples/hello-world/Cargo.toml
  examples/log/Cargo.toml
  examples/minimal/Cargo.toml
  examples/random/Cargo.toml
  examples/threading-channel/Cargo.toml
  examples/threading/Cargo.toml
  examples/usb-serial/Cargo.toml
  src/lib/clist/Cargo.toml
  src/lib/coapcore/Cargo.toml
  src/lib/coapcore/src/seccontext.rs
  src/lib/rbi/Cargo.toml
  src/lib/ringbuffer/Cargo.toml
  src/riot-rs-random/Cargo.toml
  tests/benchmarks/bench_sched_yield/Cargo.toml
Labels: CI

#378 chore(ci/hax): update github action to hax ref 533f870
  .github/workflows/hax.yml
Labels: CI, formal

#388 refactor!: remove the embassy module and all its uses
  examples/blinky/src/main.rs
  examples/blinky/src/pins.rs
  examples/coap/src/main.rs
  examples/embassy-http-server/src/main.rs
  examples/embassy-http-server/src/pins.rs
  examples/embassy-net-tcp/src/main.rs
  examples/embassy-net-udp/src/main.rs
  examples/embassy-usb-keyboard/src/main.rs
  examples/embassy/src/main.rs
  examples/gpio/src/main.rs
  examples/gpio/src/pins.rs
  examples/usb-serial/src/main.rs
  src/riot-rs-macros/src/config.rs
  src/riot-rs-macros/src/spawner.rs
  src/riot-rs-macros/src/task.rs
  src/riot-rs-macros/tests/ui/config/conflicting_config_kind.rs
  src/riot-rs-macros/tests/ui/config/misspelled_config_kind.rs
  src/riot-rs-macros/tests/ui/config/no_parameters.rs
  src/riot-rs-macros/tests/ui/spawner/async_fn.rs
  src/riot-rs-macros/tests/ui/spawner/missing_peripherals_param.rs
  src/riot-rs-macros/tests/ui/spawner/no_autostart_param.rs
  src/riot-rs-macros/tests/ui/task/missing_autostart_param_for_hook.rs
  src/riot-rs-macros/tests/ui/task/misspelled_hook_name.rs
  src/riot-rs/src/lib.rs
  tests/gpio-interrupt-nrf/src/main.rs
  tests/gpio-interrupt-stm32/src/main.rs
  tests/gpio/src/main.rs
  tests/gpio/src/pins.rs
Labels: UX

#386 ci(docs): enable missing features that should appear in the docs
  .github/workflows/build-deploy-docs.yml
  .github/workflows/main.yml
Labels: docs, CI

#375 ci: set up yamllint checking
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/workflows/dependencies-action.yml
  .github/workflows/main.yml
  .yamllint.yml
  laze-project.yml
  src/riot-rs-core/laze.yml
  src/riot-rs-rt/laze.yml
Labels: CI

#390 fix(blinky): blinky does not need `external-interrupts`
  examples/blinky/Cargo.toml
Labels: testing
