Repository ariel-os/ariel-os, pull requests merged in 2024-05, with the labels that each got.

#187 riot-rs-threads: cortex_m: make `sched()` less hacky
  src/riot-rs-threads/src/arch/cortex_m.rs
Labels: threading

#223 examples: add new `threading-channel` example
  Cargo.lock
  examples/laze.yml
  examples/threading-channel/Cargo.toml
  examples/threading-channel/README.md
  examples/threading-channel/laze.yml
  examples/threading-channel/src/main.rs
Labels: threading

#182 threads: add support for RISC-V (esp32 only)
  Cargo.lock
  src/riot-rs-threads/Cargo.toml
  src/riot-rs-threads/src/arch/cortex_m.rs
  src/riot-rs-threads/src/arch/mod.rs
  src/riot-rs-threads/src/arch/riscv.rs
  src/riot-rs-threads/src/lib.rs
Labels: arch, threading

#288 ci: drop issue metrics
  .github/workflows/issue-metrics.yml
Labels: CI, cleanup

#291 doc: update add_board_support.md
  doc/add_board_support.md
Labels: docs
