Repository ariel-os/ariel-os, pull requests merged in 2024-04, with the labels that each got.

#220 COC: fix broken link to Reporting Guidelines
  CODE_OF_CONDUCT.md
Labels: docs

#232 ci: build and publish rustdoc
  .github/workflows/rustdoc.yml
Labels: docs, CI

#238 ci: fix rustdoc workflow file
  .github/workflows/rustdoc.yml
Labels: CI

#246 ci(docs): fix the workflow trigger conditions
  .github/workflows/build-deploy-docs.yml
Labels: docs, CI

#247 docs(riot-rs): show the `thread` module in docs
  .github/workflows/build-deploy-docs.yml
  .github/workflows/main.yml
  src/riot-rs/src/lib.rs
Labels: docs, CI

#260 docs(random): fix a few typos and minor docs issues
  src/riot-rs-random/src/lib.rs
  src/riot-rs/Cargo.toml
Labels: docs

#240 ci(rustdoc): lint all crates for rustdoc errors
  .github/workflows/main.yml
Labels: docs, CI

#265 refactor(arch): use `cfg_if` to select the arch module
  src/riot-rs-embassy/src/lib.rs
Labels: arch

#259 docs(cod-conv): make linking to items mandatory when possible
  book/src/coding-conventions.md
Labels: docs

#266 refactor(arch): split the `nrf` arch into multiple submodule files
  src/riot-rs-embassy/src/arch/nrf.rs
  src/riot-rs-embassy/src/arch/nrf/hwrng.rs
  src/riot-rs-embassy/src/arch/nrf/mod.rs
  src/riot-rs-embassy/src/arch/nrf/usb.rs
  src/riot-rs-embassy/src/lib.rs
Labels: arch

#272 feat(arch): re-export Embassy gpio modules
  src/riot-rs-embassy/src/arch/dummy/gpio.rs
  src/riot-rs-embassy/src/arch/dummy/mod.rs
  src/riot-rs-embassy/src/arch/esp/gpio.rs
  src/riot-rs-embassy/src/arch/esp/mod.rs
  src/riot-rs-embassy/src/arch/nrf/gpio.rs
  src/riot-rs-embassy/src/arch/nrf/mod.rs
  src/riot-rs-embassy/src/arch/rp2040/gpio.rs
  src/riot-rs-embassy/src/arch/rp2040/mod.rs
  src/riot-rs-embassy/src/lib.rs
Labels: arch

#275 fix(floats): disable hard floats on thumbv7m-none-eabi
  laze-project.yml
Labels: arch

#276 ci(lints): use ruff to check Python formatting
  .github/workflows/main.yml
Labels: CI
