Repository ariel-os/ariel-os, pull requests merged in 2024-11, with the labels that each got.

#514 docs(thread-macro): add a missing param in the doc examples
  src/riot-rs-macros/src/thread.rs
Labels: docs, threading

#515 fix(defmt-esp): enable `defmt` on `esp-hal` when requested
  src/riot-rs-esp/Cargo.toml
Labels: arch

#517 chore(testing-rt): delete the unused `testing` module
  src/riot-rs-rt/src/lib.rs
  src/riot-rs-rt/src/testing.rs
Labels: testing

#518 docs(usb): complete and slightly improve USB docs
  src/riot-rs-arch/src/dummy/usb.rs
  src/riot-rs-embassy/src/usb.rs
Labels: docs, USB

#520 feat(spi-main): add support for SPI main on nRF52833
  src/riot-rs-nrf/src/spi/main/mod.rs
  src/riot-rs-nrf/src/spi/mod.rs
  tests/spi-loopback/laze.yml
  tests/spi-loopback/src/pins.rs
Labels: arch

#527 feat(embassy-time): re-export the crate and relevant items
  Cargo.lock
  examples/blinky/Cargo.toml
  examples/blinky/src/main.rs
  examples/coap/Cargo.toml
  examples/embassy-http-server/Cargo.toml
  examples/embassy-http-server/src/main.rs
  examples/embassy-net-tcp/Cargo.toml
  examples/embassy-net-tcp/src/main.rs
  examples/embassy-net-udp/Cargo.toml
  examples/embassy-usb-keyboard/Cargo.toml
  examples/embassy-usb-keyboard/src/main.rs
  examples/gpio/Cargo.toml
  examples/gpio/src/main.rs
  examples/thread-async-interop/Cargo.toml
  examples/thread-async-interop/src/main.rs
  examples/usb-serial/Cargo.toml
  src/riot-rs-embassy/src/lib.rs
  src/riot-rs/Cargo.toml
  tests/gpio-interrupt-nrf/Cargo.toml
  tests/gpio-interrupt-stm32/Cargo.toml
Labels: time

#530 ci(clippy): enable more Cargo features on `riot-rs-embassy`
  .github/workflows/main.yml
  src/riot-rs-embassy/src/i2c/controller/mod.rs
  src/riot-rs-embassy/src/lib.rs
  src/riot-rs-embassy/src/usb.rs
Labels: CI

#522 docs(tcp-example): clean up the TCP example
  Cargo.lock
  examples/README.md
  examples/laze.yml
  examples/tcp-echo/Cargo.toml
  examples/tcp-echo/README.md
  examples/tcp-echo/laze.yml
  examples/tcp-echo/src/main.rs
Labels: docs, network

#539 refactor(deps): use crates-io patches for esp-hal crates
  Cargo.lock
  Cargo.toml
Labels: build system

#528 chore(pedantic): make Clippy happy with `riot-rs-random`
  src/riot-rs-random/src/lib.rs
Labels: crypto

#544 docs(rp-hal): document the `riot-rs-rp` HAL crate
  src/riot-rs-embassy-common/src/spi/main/mod.rs
  src/riot-rs-rp/src/gpio.rs
  src/riot-rs-rp/src/i2c/controller/mod.rs
  src/riot-rs-rp/src/i2c/mod.rs
  src/riot-rs-rp/src/lib.rs
  src/riot-rs-rp/src/spi/main/mod.rs
  src/riot-rs-rp/src/spi/mod.rs
Labels: docs, HAL

#467 feat(esp): add support for esp32 & espressif-esp32-wroom-32
  Cargo.lock
  laze-project.yml
  src/riot-rs-boards/Cargo.toml
  src/riot-rs-boards/espressif-esp32-wroom-32/Cargo.toml
  src/riot-rs-boards/espressif-esp32-wroom-32/src/lib.rs
  src/riot-rs-boards/src/lib.rs
  src/riot-rs-debug/Cargo.toml
  src/riot-rs-esp/Cargo.toml
  src/riot-rs-esp/src/gpio.rs
  src/riot-rs-esp/src/lib.rs
  src/riot-rs-rt/Cargo.toml
  src/riot-rs-threads/Cargo.toml
  tests/gpio/src/pins.rs
Labels: HAL, board

#487 Wire up `ESP32-Sx` USB support
  Cargo.lock
  laze-project.yml
  src/riot-rs-embassy/Cargo.toml
  src/riot-rs-esp/Cargo.toml
  src/riot-rs-esp/src/lib.rs
  src/riot-rs-esp/src/usb/mod.rs
  src/riot-rs-hal/Cargo.toml
Labels: USB

#547 docs(log): Clean up the log example
  examples/README.md
  examples/log/README.md
  examples/log/src/main.rs
Labels: cleanup

#553 ci: enable `cancel-in-progress` for PR builds
  .github/workflows/main.yml
Labels: CI

#557 ci: check for leftover occurrences of the old project name
  .github/workflows/main.yml
Labels: CI

#550 docs(esp-hal): document the `ariel-os-esp` HAL crate
  src/ariel-os-esp/src/gpio.rs
  src/ariel-os-esp/src/i2c/controller/mod.rs
  src/ariel-os-esp/src/i2c/mod.rs
  src/ariel-os-esp/src/lib.rs
  src/ariel-os-esp/src/spi/main/mod.rs
  src/ariel-os-esp/src/spi/mod.rs
Labels: docs, HAL

#551 docs(stm32-hal): document the `ariel-os-stm32` HAL crate
  src/ariel-os-stm32/src/gpio.rs
  src/ariel-os-stm32/src/i2c/controller/mod.rs
  src/ariel-os-stm32/src/i2c/mod.rs
  src/ariel-os-stm32/src/lib.rs
  src/ariel-os-stm32/src/spi/main/mod.rs
  src/ariel-os-stm32/src/spi/mod.rs
Labels: docs, HAL

#531 ci(docs): render manufacturer-specific docs
  .github/workflows/build-deploy-docs.yml
  src/ariel-os-hal/src/dummy/executor.rs
  src/ariel-os-hal/src/dummy/mod.rs
  src/ariel-os-hal/src/lib.rs
Labels: docs, CI, HAL

#556 Move around CoAP examples
  Cargo.lock
  Cargo.toml
  book/src/tooling/coap.md
  examples/README.md
  examples/coap-client/Cargo.toml
  examples/coap-client/README.md
  examples/coap-client/laze.yml
  examples/coap-client/server.py
  examples/coap-client/src/main.rs
  examples/coap-server/Cargo.toml
  examples/coap-server/README.md
  examples/coap-server/client.cosekey
  examples/coap-server/client.diag
  examples/coap-server/laze.yml
  examples/coap-server/src/main.rs
  examples/laze.yml
  tests/coap/Cargo.toml
  tests/coap/README.md
  tests/coap/client.cosekey
  tests/coap/client.diag
  tests/coap/fauxhoc.py
  tests/coap/laze.yml
  tests/coap/src/main.rs
  tests/laze.yml
Labels: docs, CoAP

#536 docs: add contributing guide
  CONTRIBUTING.md
Labels: docs

#571 doc: Use of nightly features has been reduced
  README.md
Labels: docs, build system

#575 docs(README): add contributors overview
  README.md
Labels: docs

#576 docs(README): remove crossed out RIOT linking mention
  README.md
Labels: docs

#569 chore: include MIT license in repo
  CONTRIBUTING.md
  GOVERNANCE.md
  LICENSE-APACHE
  LICENSE-MIT
  README.md
Labels: cleanup

#567 ci: extract the build CI job as a separate workflow
  .github/workflows/build.yml
  .github/workflows/main.yml
Labels: CI

#580 build: use the inherited `edition` value
  examples/benchmark/Cargo.toml
  examples/minimal/Cargo.toml
  src/ariel-os-boards/ai-c3/Cargo.toml
  src/ariel-os-boards/dwm1001/Cargo.toml
  src/ariel-os-boards/espressif-esp32-c6-devkitc-1/Cargo.toml
  src/ariel-os-boards/espressif-esp32-s3-wroom-1/Cargo.toml
  src/ariel-os-boards/espressif-esp32-wroom-32/Cargo.toml
  src/ariel-os-boards/microbit-v2/Cargo.toml
  src/ariel-os-boards/microbit/Cargo.toml
  src/ariel-os-boards/nrf51/Cargo.toml
  src/ariel-os-boards/nrf52/Cargo.toml
  src/ariel-os-boards/nrf52840-mdk/Cargo.toml
  src/ariel-os-boards/nrf5340/Cargo.toml
  src/ariel-os-boards/particle-xenon/Cargo.toml
  src/ariel-os-boards/rpi-pico/Cargo.toml
  src/ariel-os-boards/st-nucleo-f401re/Cargo.toml
  src/ariel-os-boards/st-nucleo-h755zi-q/Cargo.toml
  src/ariel-os-boards/st-nucleo-wb55/Cargo.toml
  src/ariel-os-chips/Cargo.toml
  src/ariel-os-chips/rp2040/Cargo.toml
  src/ariel-os-chips/stm32/Cargo.toml
  src/ariel-os-chips/stm32f4xx/Cargo.toml
  src/ariel-os-embassy/Cargo.toml
  src/ariel-os-hal/Cargo.toml
  src/ariel-os-rt/Cargo.toml
  src/ariel-os-runqueue/Cargo.toml
  src/ariel-os-storage/Cargo.toml
  src/ariel-os-threads/Cargo.toml
  src/ariel-os-threads/et-tests/Cargo.toml
  src/lib/clist/Cargo.toml
  src/lib/rbi/Cargo.toml
  src/lib/ringbuffer/Cargo.toml
Labels: build system
