Repository ariel-os/ariel-os, pull requests merged in 2024-07, with the labels that each got.

#349 feat(threads, runqueue): derive `defmt::Format` for some types
  Cargo.lock
  src/riot-rs-runqueue/Cargo.toml
  src/riot-rs-runqueue/src/runqueue.rs
  src/riot-rs-threads/Cargo.toml
  src/riot-rs-threads/src/thread.rs
  src/riot-rs-threads/src/thread_flags.rs
  src/riot-rs/Cargo.toml
Labels: UX

#237 feat(arch): add stm32 support
  Cargo.lock
  Cargo.toml
  README.md
  _typos.toml
  laze-project.yml
  src/riot-rs-boards/Cargo.toml
  src/riot-rs-boards/nucleo-f401re/src/lib.rs
  src/riot-rs-boards/src/lib.rs
  src/riot-rs-boards/st-nucleo-f401re/Cargo.toml
  src/riot-rs-boards/st-nucleo-f401re/build.rs
  src/riot-rs-boards/st-nucleo-f401re/memory.x
  src/riot-rs-boards/st-nucleo-f401re/src/lib.rs
  src/riot-rs-boards/st-nucleo-h755zi-q/Cargo.toml
  src/riot-rs-boards/st-nucleo-h755zi-q/src/lib.rs
  src/riot-rs-boards/st-nucleo-wb55/Cargo.toml
  src/riot-rs-boards/st-nucleo-wb55/build.rs
  src/riot-rs-boards/st-nucleo-wb55/memory.x
  src/riot-rs-boards/st-nucleo-wb55/src/lib.rs
  src/riot-rs-chips/stm32/Cargo.toml
  src/riot-rs-chips/stm32/src/lib.rs
  src/riot-rs-embassy/Cargo.toml
  src/riot-rs-embassy/src/arch/stm32/mod.rs
  src/riot-rs-embassy/src/arch/stm32/usb.rs
  src/riot-rs-embassy/src/arch/stm32/usb_synopsis_otg.rs
  src/riot-rs-embassy/src/lib.rs
Labels: arch

#324 docs(book): add an initial version of the support matrix
  .github/workflows/main.yml
  book/src/SUMMARY.md
  book/src/hardware_functionality_support.md
  book/src/support_matrix.html
  doc/gen_support_matrix_html.rs
  doc/support_matrix.yml
Labels: docs, network, arch, board

#355 handle log level with laze, enable defmt with info log level by default
  Cargo.lock
  book/src/tooling/defmt.md
  examples/laze.yml
  examples/log/Cargo.toml
  examples/log/README.md
  examples/log/laze.yml
  examples/log/src/main.rs
  laze-project.yml
Labels: build system

#354 feat: default defmt logging
  Cargo.lock
  examples/benchmark/src/main.rs
  examples/coap/src/main.rs
  examples/core-sizes/src/main.rs
  examples/embassy-http-server/Cargo.toml
  examples/embassy-http-server/src/main.rs
  examples/embassy-net-tcp/src/main.rs
  examples/embassy-net-udp/src/main.rs
  examples/embassy-usb-keyboard/src/main.rs
  examples/embassy/src/main.rs
  examples/hello-world-async/src/main.rs
  examples/hello-world/src/main.rs
  examples/random/src/main.rs
  examples/threading-channel/src/main.rs
  examples/threading/src/main.rs
  src/riot-rs-bench/Cargo.toml
  src/riot-rs-bench/src/lib.rs
  src/riot-rs-boards/ai-c3/src/lib.rs
  src/riot-rs-boards/dwm1001/src/lib.rs
  src/riot-rs-boards/espressif-esp32-c6-devkitc-1/src/lib.rs
  src/riot-rs-boards/microbit-v2/src/lib.rs
  src/riot-rs-boards/microbit/src/lib.rs
  src/riot-rs-boards/nrf51/src/lib.rs
  src/riot-rs-boards/nrf52/src/lib.rs
  src/riot-rs-boards/nrf52840-mdk/src/lib.rs
  src/riot-rs-boards/nrf52840dk/src/lib.rs
  src/riot-rs-boards/nrf52dk/src/lib.rs
  src/riot-rs-boards/nrf5340/src/lib.rs
  src/riot-rs-boards/nrf5340dk/src/lib.rs
  src/riot-rs-boards/particle-xenon/src/lib.rs
  src/riot-rs-boards/rpi-pico/src/lib.rs
  src/riot-rs-embassy/Cargo.toml
  src/riot-rs-embassy/src/arch/esp/mod.rs
  src/riot-rs-embassy/src/lib.rs
  src/riot-rs-embassy/src/wifi/cyw43.rs
  src/riot-rs-embassy/src/wifi/esp_wifi.rs
  src/riot-rs-rt/src/cortexm.rs
  src/riot-rs-rt/src/lib.rs
  src/riot-rs/Cargo.toml
Labels: UX

#353 fix(task-macro): make the `riot_rs::task` macro work with no parameters
  src/riot-rs-macros/src/task.rs
Labels: UX

#362 ci(stm32): enable testing for some STM32 boards when making PRs
  .github/workflows/main.yml
Labels: CI, arch, testing

#363 fix(atomics): clarify how we select portable-atomic's atomic implementations
  Cargo.toml
  src/riot-rs-rt/Cargo.toml
Labels: arch, threading

#364 fix(laze): add `stm32` to the implementors of `sw/benchmark`
  laze-project.yml
Labels: arch, testing

#367 ci: increase the number of parallel jobs
  .github/workflows/main.yml
Labels: CI
