Repository ariel-os/ariel-os, pull requests merged in 2024-09, with the labels that each got.

#394 ci(cargo-deny): force the installation when already restored from cache
  .github/workflows/main.yml
Labels: CI

#395 docs(spawner-macro): add a missing parameter in a doc example
  src/riot-rs-macros/src/spawner.rs
Labels: docs, UX

#396 docs(esp): mark User USB as not currently supported
  book/src/support_matrix.html
  doc/support_matrix.yml
Labels: docs, USB

#391 chore(lints): set more documentation-related lints to `deny`
  Cargo.toml
  src/lib/coapcore/src/lib.rs
  src/lib/coapcore/src/seccontext.rs
Labels: docs, CI

#366 docs(governance): create governance doc
  GOVERNANCE.md
Labels: docs

#407 ci(matrix-bot): notify of `ready_for_review` events
  .github/workflows/matrix-bot.yml
Labels: CI

#412 build(profiles): make the `dev` profile suitable for embedded
  Cargo.toml
Labels: build system

#409 refactor(runqueue): use `Option::map` as hax now supports it
  src/riot-rs-runqueue/src/runqueue.rs
Labels: formal

#381 feat(threads): sort `ThreadList` by priority
  Cargo.lock
  Cargo.toml
  src/riot-rs-threads/src/threadlist.rs
  tests/laze.yml
  tests/threading-lock/Cargo.toml
  tests/threading-lock/laze.yml
  tests/threading-lock/src/main.rs
Labels: threading

#369 fix(threads/cortex_m): don't save high regs on first schedule
  src/riot-rs-threads/src/arch/cortex_m.rs
Labels: threading

#417 chore(hax): update the Makefile with upstream
  _typos.toml
  src/riot-rs-runqueue/proofs/fstar/extraction/Makefile
Labels: formal

#414 refactor(runqueue): implement `Default` now that hax supports it
  .github/workflows/hax.yml
  Cargo.lock
  src/riot-rs-runqueue/Cargo.toml
  src/riot-rs-runqueue/src/runqueue.rs
Labels: threading

#424 fix(stm32): fix the executor-interrupt mode
  laze-project.yml
  src/riot-rs-embassy/Cargo.toml
  src/riot-rs-stm32/build.rs
  src/riot-rs-stm32/src/lib.rs
Labels: arch, threading

#382 refactor(threads): improve panic handling and docs
  src/riot-rs-threads/src/channel.rs
  src/riot-rs-threads/src/lib.rs
  src/riot-rs-threads/src/lock.rs
  src/riot-rs-threads/src/threadlist.rs
Labels: threading

#437 ci(clippy): fail the `lint` job on clippy warnings
  .github/workflows/main.yml
Labels: CI

#399 feat(xtensa): add support for esp32s3 with xtensa arch
  .github/workflows/main.yml
  Cargo.lock
  laze-project.yml
  src/riot-rs-bench/Cargo.toml
  src/riot-rs-bench/src/esp.rs
  src/riot-rs-bench/src/lib.rs
  src/riot-rs-boards/Cargo.toml
  src/riot-rs-boards/espressif-esp32-s3-wroom-1/Cargo.toml
  src/riot-rs-boards/espressif-esp32-s3-wroom-1/src/lib.rs
  src/riot-rs-boards/src/lib.rs
  src/riot-rs-debug/Cargo.toml
  src/riot-rs-esp/Cargo.toml
  src/riot-rs-esp/src/lib.rs
  src/riot-rs-rt/Cargo.toml
  src/riot-rs-rt/build.rs
  src/riot-rs-rt/linkme-esp32c3-fixup.x
  src/riot-rs-rt/linkme-esp32c6-fixup.x
  src/riot-rs-threads/Cargo.toml
  src/riot-rs-threads/src/arch/mod.rs
  src/riot-rs-threads/src/arch/riscv.rs
  src/riot-rs-threads/src/arch/xtensa.rs
  src/riot-rs-threads/src/lib.rs
  tests/benchmarks/bench_sched_yield/laze.yml
Labels: arch

#370 feat(threads): dynamic thread priorities
  Cargo.lock
  Cargo.toml
  src/riot-rs-runqueue/src/lib.rs
  src/riot-rs-runqueue/src/runqueue.rs
  src/riot-rs-threads/src/lib.rs
  tests/laze.yml
  tests/threading-dynamic-prios/Cargo.toml
  tests/threading-dynamic-prios/laze.yml
  tests/threading-dynamic-prios/src/main.rs
Labels: threading
