Repository ariel-os/ariel-os, pull requests merged in 2024-03, with the labels that each got.

#142 style(gh-workflows): fix YAML indentation
  .github/workflows/book.yml
  .github/workflows/git.yml
  .github/workflows/main.yml
  .github/workflows/matrix-bot.yml
Labels: CI

#176 ci: add nightly build
  .github/workflows/main.yml
Labels: CI

#159 threads: extract arch-independent scheduling logic
  src/riot-rs-threads/src/arch/cortex_m.rs
  src/riot-rs-threads/src/arch/mod.rs
  src/riot-rs-threads/src/lib.rs
  src/riot-rs-threads/src/thread.rs
  src/riot-rs-threads/src/thread_flags.rs
  src/riot-rs-threads/src/threadlist.rs
Labels: threading

#100 feat(config): add a `config` attribute macro
  Cargo.lock
  examples/embassy-http-server/Cargo.toml
  examples/embassy-http-server/src/main.rs
  examples/embassy-net-tcp/src/main.rs
  examples/embassy-net-udp/src/main.rs
  examples/embassy-usb-keyboard/Cargo.toml
  examples/embassy-usb-keyboard/src/main.rs
  laze-project.yml
  src/riot-rs-embassy/src/lib.rs
  src/riot-rs-embassy/src/network.rs
  src/riot-rs-embassy/src/usb.rs
  src/riot-rs-macros/Cargo.toml
  src/riot-rs-macros/src/config.rs
  src/riot-rs-macros/src/lib.rs
  src/riot-rs-macros/tests/macro_errors.rs
  src/riot-rs-macros/tests/ui/config_conflicting_config_kind.rs
  src/riot-rs-macros/tests/ui/config_conflicting_config_kind.stderr
  src/riot-rs-macros/tests/ui/config_misspelled_config_kind.rs
  src/riot-rs-macros/tests/ui/config_misspelled_config_kind.stderr
  src/riot-rs-macros/tests/ui/config_no_parameters.rs
  src/riot-rs-macros/tests/ui/config_no_parameters.stderr
  src/riot-rs/src/lib.rs
Labels: UX

#154 README: updated text
  README.md
Labels: docs

#163 Add Code of Conduct
  CODE_OF_CONDUCT.md
  book/src/COC_reporting.md
  book/src/CODE_OF_CONDUCT.md
  book/src/SUMMARY.md
Labels: docs

#184 examples/threading: remove obsolete `riot_main()`
  examples/threading/src/main.rs
Labels: cleanup

#183 riot-rs-threads: fix channel returning wrong values
  src/riot-rs-threads/src/channel.rs
Labels: threading

#195 README: nrf5340, microbit-v2 and esp32-C6 added in supported list and…
  README.md
Labels: docs, project-onboarding

#207 Book: fix path to intro diagram
  book/src/figures/RIOT-rs-arch-diagram1.svg
  book/src/introduction.md
Labels: docs

#211 ci: add action enforcing PR dependencies
  .github/workflows/dependencies-action.yml
Labels: CI

#204 refactor(config-macro): move trybuild tests
  src/riot-rs-macros/tests/macro_errors.rs
  src/riot-rs-macros/tests/ui/config/conflicting_config_kind.rs
  src/riot-rs-macros/tests/ui/config/conflicting_config_kind.stderr
  src/riot-rs-macros/tests/ui/config/misspelled_config_kind.rs
  src/riot-rs-macros/tests/ui/config/misspelled_config_kind.stderr
  src/riot-rs-macros/tests/ui/config/no_parameters.rs
  src/riot-rs-macros/tests/ui/config/no_parameters.stderr
Labels: testing
