Repository ariel-os/ariel-os, pull requests merged in 2025-03, with the labels that each got.

#870 docs(networking): document the previously missing `network` laze module
  book/src/networking.md
Labels: docs, network

#885 refactor(stm32): replace Cargo features with laze capabilities
  laze-project.yml
  src/ariel-os-boards/st-nucleo-h755zi-q/Cargo.toml
  src/ariel-os-boards/st-nucleo-wb55/Cargo.toml
  src/ariel-os-boards/st-nucleo-wba55/Cargo.toml
  src/ariel-os-stm32/Cargo.toml
  src/ariel-os-stm32/src/hwrng.rs
  src/ariel-os-stm32/src/lib.rs
Labels: HAL, build system

#896 docs(runqueue): document the remaining items
  src/ariel-os-runqueue/src/lib.rs
  src/ariel-os-runqueue/src/runqueue.rs
Labels: docs, threading

#895 docs(threads): document the remaining items
  src/ariel-os-threads/src/lib.rs
  src/ariel-os-threads/src/sync/channel.rs
  src/ariel-os-threads/src/thread_flags.rs
Labels: docs, threading

#846 ci: split lint steps
  .github/workflows/main.yml
Labels: CI, ci-build:skip

#901 docs(README): add current logo
  README.md
  book/src/figures/ariel-hexacube-orange-rounded.svg
Labels: docs

#908 docs(logo): Use paths and not text in logo
  book/src/figures/ariel-hexacube-orange-rounded.svg
Labels: docs

#881 refactor(laze): reorder and fix Arm-related modules
  laze-project.yml
Labels: build system

#889 feat(stm32): add support for non-`USB_LP` USB drivers
  laze-project.yml
  src/ariel-os-stm32/src/lib.rs
  src/ariel-os-stm32/src/usb.rs
Labels: HAL, build system, USB

#911 feat(stm32): introduce laze capabilities for all HWRNG interrupts
  src/ariel-os-stm32/src/hwrng.rs
Labels: HAL

#912 refactor(laze): expose `cortex-m*` modules as `cfg` flags
  laze-project.yml
  src/ariel-os-rt/Cargo.toml
Labels: build system

#891 ci(cargo-test): enable `rust-cache` for the `cargo-test` job
  .github/workflows/main.yml
Labels: CI

#918 fix(task-macro): avoid the need for importing `UsbBuilderHook`
  src/ariel-os-macros/src/task.rs
Labels: UX

#923 refactor: remove unneeded `UsbBuilderHook` imports
  examples/usb-keyboard/src/main.rs
  examples/usb-serial/src/main.rs
  src/ariel-os-macros/src/task.rs
  src/ariel-os-macros/tests/ui/task/missing_autostart_param_for_hook.rs
  src/ariel-os-macros/tests/ui/task/missing_autostart_param_for_hook.stderr
  src/ariel-os-macros/tests/ui/task/misspelled_hook_name.rs
  src/ariel-os-macros/tests/ui/task/misspelled_hook_name.stderr
Labels: docs

#917 refactor(power)!: simplify the `power::reboot()` implementation
  .github/workflows/build-deploy-docs.yml
  .github/workflows/main.yml
  Cargo.lock
  examples/README.md
  examples/power/Cargo.toml
  examples/power/README.md
  examples/power/src/main.rs
  src/ariel-os-power/Cargo.toml
  src/ariel-os-power/src/lib.rs
  src/ariel-os/Cargo.toml
  src/ariel-os/src/lib.rs
Labels: HAL

#922 docs(examples): rename examples with confusing laze module names
  Cargo.lock
  examples/benchmark/Cargo.toml
  examples/benchmark/laze.yml
  examples/storage/Cargo.toml
  examples/storage/laze.yml
  examples/testing/Cargo.toml
  examples/testing/laze.yml
  examples/threading/Cargo.toml
  examples/threading/laze.yml
  examples/usb-serial/Cargo.toml
  examples/usb-serial/laze.yml
Labels: docs

#902 feat(coap): express unauthenticated credentials
  src/ariel-os-coap/build.rs
  src/ariel-os-coap/src/stored.rs
  tests/coap/README.md
  tests/coap/peers.yml
Labels: CoAP

#931 perf(storage): block on storage init to spare RAM
  src/ariel-os-embassy/src/lib.rs
  src/ariel-os-storage/src/lib.rs
Labels: HAL, storage

#933 fix(coap): remove needless use of ReportingHandlerBuilder
  examples/coap-server/src/main.rs
  tests/coap-blinky/src/main.rs
Labels: CoAP

#932 refactor(coap): move stack size into module
  examples/coap-client/laze.yml
  examples/coap-server/laze.yml
  laze-project.yml
  tests/coap-blinky/laze.yml
  tests/coap/laze.yml
Labels: build system

#928 feat(stm32): codegen a crate enabling the right `embassy-stm32` feature
  Cargo.lock
  _typos.toml
  src/ariel-os-stm32-mapping/Cargo.toml
  src/ariel-os-stm32-mapping/build.rs
  src/ariel-os-stm32-mapping/src/lib.rs
  src/ariel-os-stm32-mapping/stm32_mapping.csv
  src/ariel-os-stm32/Cargo.toml
Labels: HAL, build system

#947 ci: free up space
  .github/workflows/build.yml
Labels: CI

#848 refactor(laze): invert how capabilities are provided
  examples/benchmark/laze.yml
  laze-project.yml
  tests/benchmarks/bench_sched_flags/laze.yml
  tests/benchmarks/bench_sched_yield/laze.yml
Labels: HAL, build system

#919 feat(stm32): add support for low-priority USB interrupts
  src/ariel-os-stm32/src/usb.rs
Labels: HAL, build system, USB

#944 fix(boards): fix the context `rpi-pico-w` inherits from
  laze-project.yml
Labels: board, build system

#925 refactor(stm32): unify the USB module to ease future changes
  src/ariel-os-stm32/src/lib.rs
  src/ariel-os-stm32/src/usb.rs
  src/ariel-os-stm32/src/usb_synopsis_otg.rs
Labels: HAL, USB

#921 docs(book): turn underscores into dashes in page slugs
  README.md
  book/book.toml
  book/src/SUMMARY.md
  book/src/adding-board-support.md
  book/src/async-support.md
  book/src/build-system.md
  book/src/debug-console.md
  book/src/getting-started.md
  book/src/hardware-functionality-support.md
  book/src/introduction.md
  book/src/multithreading.md
  book/src/networking.md
  book/src/randomness.md
  book/src/storage.md
  book/src/testing.md
  book/src/tooling/coap.md
  src/ariel-os-hal/src/lib.rs
Labels: docs

#953 fix(rp): mark `link_section` as `unsafe`
  src/ariel-os-rp/src/picotool.rs
Labels: bug

#945 docs(logo): Update logo to latest SVG variant
  book/src/figures/ariel-hexacube-orange-rounded.svg
Labels: docs

#926 feat(nrf): add basic support for nRF9160
  doc/support_matrix.yml
  examples/blinky/laze.yml
  examples/blinky/src/pins.rs
  examples/gpio/laze.yml
  examples/gpio/src/pins.rs
  examples/http-server/laze.yml
  examples/http-server/src/pins.rs
  laze-project.yml
  src/ariel-os-nrf/Cargo.toml
  src/ariel-os-nrf/build.rs
  src/ariel-os-nrf/src/i2c/controller/mod.rs
  src/ariel-os-nrf/src/i2c/mod.rs
  src/ariel-os-nrf/src/identity.rs
  src/ariel-os-nrf/src/lib.rs
  src/ariel-os-nrf/src/spi/main/mod.rs
  src/ariel-os-nrf/src/spi/mod.rs
  src/ariel-os-storage/build.rs
  tests/coap-blinky/laze.yml
  tests/gpio-interrupt-nrf/src/main.rs
  tests/gpio/src/pins.rs
  tests/i2c-controller/laze.yml
  tests/i2c-controller/src/pins.rs
  tests/spi-loopback/laze.yml
  tests/spi-loopback/src/pins.rs
  tests/spi-main/laze.yml
  tests/spi-main/src/pins.rs
Labels: HAL, board, chip

#954 docs: update storage.md
  book/src/storage.md
Labels: docs
