Repository ariel-os/ariel-os, pull requests merged in 2025-10, with the labels that each got.

#1339 feat(random): Add support for getrandom
  .github/workflows/main.yml
  Cargo.lock
  laze-project.yml
  src/ariel-os-random/Cargo.toml
  src/ariel-os-random/src/lib.rs
Labels: crypto, ci-build:small

#1416 docs(random): document support for the `getrandom` crate
  book/src/randomness.md
  src/ariel-os/Cargo.toml
Labels: docs, crypto, ci-build:skip

#1423 docs(gen-book): rewrite board page support matrix table in Markdown
  book/src/boards/bbc-microbit-v1.md
  book/src/boards/bbc-microbit-v2.md
  book/src/boards/espressif-esp32-c3-lcdkit.md
  book/src/boards/espressif-esp32-c6-devkitc-1.md
  book/src/boards/espressif-esp32-s3-devkitc-1.md
  book/src/boards/heltec-wifi-lora-32-v3.md
  book/src/boards/nordic-thingy-91-x-nrf9151.md
  book/src/boards/nrf52840dk.md
  book/src/boards/nrf52dk.md
  book/src/boards/nrf5340dk.md
  book/src/boards/nrf9160dk-nrf9160.md
  book/src/boards/rpi-pico-w.md
  book/src/boards/rpi-pico.md
  book/src/boards/rpi-pico2-w.md
  book/src/boards/rpi-pico2.md
  book/src/boards/seeedstudio-lora-e5-mini.md
  book/src/boards/st-b-l475e-iot01a.md
  book/src/boards/st-nucleo-c031c6.md
  book/src/boards/st-nucleo-f042k6.md
  book/src/boards/st-nucleo-f401re.md
  book/src/boards/st-nucleo-f411re.md
  book/src/boards/st-nucleo-h755zi-q.md
  book/src/boards/st-nucleo-wb55.md
  book/src/boards/st-nucleo-wba55.md
  book/src/boards/st-steval-mkboxpro.md
  book/src/boards/stm32u083c-dk.md
  book/templates/board-page.md.tmpl
Labels: docs, ci-build:skip
