Repository ariel-os/ariel-os, pull requests merged in 2025-06, with the labels that each got.

#1068 feat(nrf): Add support for BBC micro:bit v1
  doc/support_matrix.yml
  examples/blinky/laze.yml
  examples/blinky/src/main.rs
  examples/blinky/src/pins.rs
  examples/gpio/laze.yml
  examples/gpio/src/main.rs
  examples/gpio/src/pins.rs
  laze-project.yml
  src/ariel-os-nrf/Cargo.toml
  src/ariel-os-nrf/build.rs
  src/ariel-os-nrf/src/lib.rs
  tests/gpio-interrupt-nrf/src/main.rs
  tests/gpio/src/pins.rs
Labels: board, chip

#1071 docs(examples): add a new `i2c-scanner` example
  Cargo.lock
  examples/i2c-scanner/Cargo.toml
  examples/i2c-scanner/README.md
  examples/i2c-scanner/laze.yml
  examples/i2c-scanner/src/main.rs
  examples/i2c-scanner/src/pins.rs
  examples/laze.yml
Labels: docs

#1075 ci(build-workflow): enable `fail-fast` for the matrix
  .github/workflows/build.yml
Labels: CI

#1076 docs(README): add missing `i2c-scanner`
  examples/README.md
Labels: docs

#843 ci(build): restrict build runs based on PR labels
  .github/workflows/build.yml
Labels: CI, ci-build:small

#1069 feat(ble): add public interface for BLE functionality
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  deny.toml
  laze-project.yml
  src/ariel-os-embassy-common/Cargo.toml
  src/ariel-os-embassy-common/src/ble.rs
  src/ariel-os-embassy-common/src/lib.rs
  src/ariel-os-embassy/Cargo.toml
  src/ariel-os-embassy/src/ble.rs
  src/ariel-os-embassy/src/lib.rs
  src/ariel-os-hal/Cargo.toml
  src/ariel-os-hal/src/dummy/ble.rs
  src/ariel-os-hal/src/dummy/mod.rs
  src/ariel-os-macros/src/config.rs
  src/ariel-os/Cargo.toml
Labels: ci-build:small, BLE

#1092 docs: Add OpenSSF best practices badge to README.md
  README.md
Labels: docs, ci-build:small

#1090 docs(config)!: remove the `network-config-static` feature from the docs
  src/ariel-os/Cargo.toml
Labels: docs, ci-build:small, breaking

#1098 fix(rp235x): fix non-deterministic panics at startup when using the TRNG
  Cargo.lock
  ariel-os-cargo.toml
Labels: ci-build:small

#1104 fix(nrf): fix build for nrf5340-net
  laze-project.yml
  src/ariel-os-storage/build.rs
  src/ariel-os-storage/src/lib.rs
  tests/gpio-interrupt-nrf/laze.yml
Labels: bug, HAL, ci-build:small

#1102 feat(nrf53-net): add hwrng support
  laze-project.yml
  src/ariel-os-nrf/src/hwrng.rs
Labels: board, ci-build:small

#1106 fix(deps): disable static cell `nightly` feature
  Cargo.toml
Labels: ci-build:small

#1108 chore: add changelog for v0.2.1
  CHANGELOG.md
Labels: docs, ci-build:small

#1109 feat(build): pass through task arguments where useful
  laze-project.yml
Labels: ci-build:small, breaking

#1112 feat(coapcore): Use defmt_or_log's enhanced hex and CBOR outputs
  Cargo.lock
  src/lib/coapcore/Cargo.toml
  src/lib/coapcore/src/ace.rs
  src/lib/coapcore/src/seccfg.rs
  src/lib/coapcore/src/seccontext.rs
Labels: ci-build:small

#1049 feat(build): add vscode configuration generator
  book/book.toml
  book/src/SUMMARY.md
  book/src/build-system.md
  book/src/vscode-configuration.md
  laze-project.yml
  scripts/vscode.rs
Labels: build system, ci-build:small
