Repository ariel-os/ariel-os, pull requests merged in 2025-09, with the labels that each got.

#1287 chore(deps): remove `konst` from the workspace manifest as it is unused
  Cargo.toml
Labels: ci-build:skip

#1320 chore(ariel-os-coap): remove the unused `embassy-futures` dependency
  Cargo.lock
  src/ariel-os-coap/Cargo.toml
Labels: CoAP, ci-build:rp

#1319 refactor(i2c): replace `embassy-futures`'s `select` with `with_timeout`
  Cargo.lock
  src/ariel-os-embassy-common/Cargo.toml
  src/ariel-os-embassy-common/src/i2c/controller/mod.rs
  src/ariel-os-embassy-common/src/lib.rs
Labels: ci-build:small

#1322 refactor(ci): move `cargo-manifest-check` out of the `lint` CI job
  .github/workflows/main.yml
Labels: CI, ci-build:skip

#1312 fix(ble): propagate the `defmt` feature to `trouble-host` when enabled
  Cargo.lock
  src/ariel-os-embassy/Cargo.toml
Labels: ci-build:small, BLE

#1324 docs: Add Mastodon badge to README.md
  README.md
Labels: docs, ci-build:skip

#1212 feat(support-matrix): collect all errors instead of one
  doc/gen_support_matrix_html.rs
Labels: docs, enhancement, ci-build:skip

#1343 fix(coap): use unmaintained `serde_yaml` instead of unsound `serde_yml`
  Cargo.lock
  src/ariel-os-coap/Cargo.toml
  src/ariel-os-coap/build.rs
Labels: CoAP, ci-build:rp

#1329 feat(time): provide a `with_timeout()` helper by re-exporting Embassy's
  src/ariel-os-embassy/src/lib.rs
Labels: time, changelog:highlight, ci-build:rp

#1296 ci: add `cargo-vet` to the CI process
  .github/workflows/main.yml
  .github/workflows/vetting.yml
  supply-chain/audits.toml
  supply-chain/config.toml
  supply-chain/imports.lock
Labels: CI, ci-build:skip

#1331 docs(book): document our current dependency vetting process
  book/src/development-processes.md
Labels: docs, ci-build:skip

#1335 test(sensors): make host tests run for `ariel-os-sensors` as well
  src/ariel-os-sensors/Cargo.toml
  src/ariel-os-sensors/laze.yml
  src/laze.yml
Labels: testing, sensor api, ci-build:skip

#1353 doc(api): fix typo in resource section
  src/ariel-os/src/lib.rs
Labels: docs, changelog:skip, ci-build:skip

#1336 feat(net): expose a Cargo feature to enable support for multicast
  .github/workflows/build-deploy-docs.yml
  .github/workflows/main.yml
  src/ariel-os-embassy/Cargo.toml
  src/ariel-os/Cargo.toml
Labels: changelog:highlight, ci-build:rp

#1346 refactor: introduce the `ram-small` module for MCUs unable to do HTTP
  examples/http-client/laze.yml
  examples/http-server/laze.yml
  laze-project.yml
Labels: ci-build:stm32

#1362 ci: relax `rust-version` key check
  .github/workflows/main.yml
Labels: ci-build:skip

#1373 feat: add units, categories and labels for GNSS
  src/ariel-os-sensors/src/category.rs
  src/ariel-os-sensors/src/label.rs
  src/ariel-os-sensors/src/measurement_unit.rs
Labels: sensor api, ci-build:skip

#1360 refactor(sensors): make `Sensors` and `ReadingChannels` structs instead
  src/ariel-os-macros/src/define_count_adjusted_sensor_enums.rs
Labels: sensor api, ci-build:skip

#1348 refactor(network): clarify the names of IPv4-only laze modules
  book/src/networking.md
  laze-project.yml
Labels: network, ci-build:rp

#1352 docs(book): add urls to other doc resources
  book/src/introduction.md
Labels: docs, ci-build:skip

#1122 docs: add ROADMAP.md
  README.md
  ROADMAP.md
Labels: docs, ci-build:skip

#1384 refactor(docs): move support matrix schema in external module
  doc/gen_support_matrix_html.rs
  doc/schema.rs
Labels: docs, ci-build:skip

#1388 refactor(stm32): move the RCC config to a dedicated pure function
  src/ariel-os-stm32/src/lib.rs
Labels: HAL, ci-build:stm32

#1376 feat(book): add option to fold book sub-chapters
  book/book.toml
Labels: docs, ci-build:skip

#1404 style: format `ariel-os-macros` `include!`d files
  src/ariel-os-macros/src/define_count_adjusted_sensor_enums.rs
Labels: ci-build:skip

#1183 feat(stm32): add support for the STM32U073KC
  doc/support_matrix.yml
  examples/gpio/src/pins.rs
  laze-project.yml
  src/ariel-os-stm32/src/i2c/controller/mod.rs
  src/ariel-os-stm32/src/i2c/mod.rs
  src/ariel-os-stm32/src/lib.rs
  src/ariel-os-stm32/src/spi/main/mod.rs
  src/ariel-os-stm32/src/spi/mod.rs
  src/ariel-os-storage/build.rs
  tests/i2c-controller/src/pins.rs
  tests/spi-loopback/src/pins.rs
  tests/spi-main/src/pins.rs
Labels: chip, ci-build:stm32

#1361 chore(sensor-drivers): introduce a subdirectory for sensor drivers
  src/laze.yml
  src/sensors/laze.yml
Labels: sensor, ci-build:skip
