Repository ariel-os/ariel-os, pull requests merged in 2025-07, with the labels that each got.

#1116 feat(random): add RNG that can be shared between threads
  src/ariel-os-random/src/lib.rs
Labels: ci-build:small

#1118 fix(nrf-ble): restrict the `has_nrf_ble` laze module to `nrf`
  laze-project.yml
Labels: HAL, ci-build:small, BLE

#1088 docs(ble): BLE examples
  Cargo.lock
  examples/README.md
  examples/ble-advertiser/Cargo.toml
  examples/ble-advertiser/README.md
  examples/ble-advertiser/laze.yml
  examples/ble-advertiser/src/main.rs
  examples/ble-scanner/Cargo.toml
  examples/ble-scanner/README.md
  examples/ble-scanner/laze.yml
  examples/ble-scanner/src/main.rs
  examples/laze.yml
Labels: docs, ci-build:small, BLE

#1123 chore(ci): bump `typos` action to 1.34.0
  .github/workflows/main.yml
  src/ariel-os-runqueue/README.md
Labels: CI, ci-build:small

#1117 feat(stm32): add initial stm32u585 / steval-mkboxpro support
  Cargo.lock
  doc/support_matrix.yml
  examples/blinky/laze.yml
  examples/blinky/src/pins.rs
  examples/gpio/laze.yml
  examples/gpio/src/pins.rs
  examples/i2c-scanner/laze.yml
  examples/i2c-scanner/src/pins.rs
  laze-project.yml
  src/ariel-os-stm32/Cargo.toml
  src/ariel-os-stm32/src/i2c/controller/mod.rs
  src/ariel-os-stm32/src/i2c/mod.rs
  src/ariel-os-stm32/src/lib.rs
  src/ariel-os-stm32/src/spi/main/mod.rs
  src/ariel-os-stm32/src/spi/mod.rs
  src/ariel-os-stm32/src/usb.rs
  src/ariel-os-storage/build.rs
  src/ariel-os-utils/src/env.rs
  tests/spi-loopback/laze.yml
  tests/spi-loopback/src/pins.rs
  tests/spi-main/laze.yml
  tests/spi-main/src/main.rs
  tests/spi-main/src/pins.rs
Labels: board, ci-build:small, chip

#1132 fix(threads): fix some warnings in cortex-m non-hardfault case
  src/ariel-os-threads/src/arch/cortex_m.rs
Labels: threading, ci-build:small

#1136 fix(ci): enable `defmt` Cargo feature in main Clippy action
  .github/workflows/main.yml
  src/ariel-os-debug-log/src/lib.rs
Labels: CI, ci-build:small

#1135 ci(build): skip the Build when the `ci-build:skip` label is attached
  .github/workflows/build.yml
Labels: CI, ci-build:small

#1131 refactor(threads): use pointer for thread function
  src/ariel-os-threads/src/arch/cortex_m.rs
  src/ariel-os-threads/src/arch/mod.rs
  src/ariel-os-threads/src/arch/riscv.rs
  src/ariel-os-threads/src/arch/xtensa.rs
  src/ariel-os-threads/src/lib.rs
Labels: threading, ci-build:small

#1130 docs(book): update the installation command for `espup`
  book/src/getting-started.md
Labels: docs, ci-build:skip

#1134 docs(thread-macro): document the `affinity` macro parameter
  book/src/multithreading.md
  src/ariel-os-macros/src/thread.rs
Labels: docs, threading, ci-build:skip

#1137 refactor(hal): split dummy module
  src/ariel-os-hal/src/dummy/identity.rs
  src/ariel-os-hal/src/dummy/mod.rs
  src/ariel-os-hal/src/dummy/peripheral.rs
Labels: ci-build:small

#1140 docs(config): use a dedicated "Errors" section in macro docs
  src/ariel-os-utils/src/env.rs
Labels: docs, config, ci-build:skip

#1146 docs(config-macro): correct `reexports` module name
  src/ariel-os-macros/src/config.rs
Labels: docs, config, BLE, ci-build:skip

#1149 docs(book): update the installation command for espflash
  book/src/getting-started.md
Labels: docs, ci-build:skip

#1151 docs(book): pin espflash to 3.3.0
  book/src/getting-started.md
Labels: docs, ci-build:skip

#1152 fix(debug): actually compare log level in `log` backend
  src/ariel-os-debug/src/lib.rs
Labels: bug, ci-build:small, debug-output

#1154 fix(lint): allow `crate_in_macro_def` Clippy lint
  src/ariel-os-embassy-common/src/executor_swi.rs
Labels: ci-build:skip

#1100 feat(ble): support BLE on nrf5340 network core
  Cargo.lock
  Cargo.toml
  laze-project.yml
  src/ariel-os-nrf/Cargo.toml
  src/ariel-os-nrf/src/ble.rs
  src/ariel-os-nrf/src/irqs.rs
Labels: HAL, ci-build:small, BLE

#647 feat: native board
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
  ariel-os-cargo.toml
  examples/testing/laze.yml
  laze-project.yml
  src/ariel-os-alloc/src/lib.rs
  src/ariel-os-bench/src/lib.rs
  src/ariel-os-bench/src/native.rs
  src/ariel-os-debug/Cargo.toml
  src/ariel-os-debug/src/lib.rs
  src/ariel-os-hal/Cargo.toml
  src/ariel-os-hal/src/dummy/mod.rs
  src/ariel-os-hal/src/lib.rs
  src/ariel-os-native/Cargo.toml
  src/ariel-os-native/src/lib.rs
  src/ariel-os-power/src/lib.rs
  src/ariel-os-rt/src/lib.rs
  src/ariel-os-rt/src/native.rs
  src/ariel-os-runqueue/src/lib.rs
  src/ariel-os-threads/Cargo.toml
  src/ariel-os-threads/src/arch/mod.rs
  src/ariel-os-threads/src/arch/native.rs
  src/ariel-os-threads/src/arch/native/critical_section.rs
  src/ariel-os-threads/src/arch/native/critical_section/upstream.rs
  src/ariel-os-threads/src/lib.rs
  src/ariel-os/Cargo.toml
  tests/gpio/laze.yml
  tests/threading-lock/laze.yml
Labels: threading, board, ci-build:small

#1157 feat(native): wire up hwrng
  laze-project.yml
  src/ariel-os-hal/Cargo.toml
  src/ariel-os-native/Cargo.toml
  src/ariel-os-native/src/hwrng.rs
  src/ariel-os-native/src/lib.rs
Labels: board, ci-build:small

#1162 fix(threads): fix `current_tid()`
  src/ariel-os-threads/src/lib.rs
Labels: bug, threading, ci-build:small

#1158 ci(build-pr-labels): introduce even more build labels
  .github/workflows/build.yml
Labels: CI, ci-build:native

#1167 ci(build): install the Xtensa toolchain only when needed
  .github/workflows/build.yml
Labels: CI, ci-build:native

#1171 fix(deps): use revision instead of branch
  Cargo.lock
  ariel-os-cargo.toml
Labels: build system, ci-build:small

#1173 feat(build): shallow clone git dependencies
  .cargo/config.toml
Labels: build system, ci-build:small

#1184 docs(wifi-book): update the list of boards having the CYW43 chip
  book/src/networking.md
Labels: docs, ci-build:skip

#1187 refactor(coap): avoid parsing a string to create a listening address
  src/ariel-os-coap/src/lib.rs
Labels: CoAP, ci-build:rp
