Repository ariel-os/ariel-os, pull requests merged in 2025-04, with the labels that each got.

#952 feat(threads): don't use `feature(naked_functions)`
  src/ariel-os-threads/src/arch/cortex_m.rs
  src/ariel-os-threads/src/lib.rs
Labels: threading

#958 chore(stm32): drop unneeded info from probe-rs chip names
  book/src/adding-board-support.md
  laze-project.yml
Labels: build system

#961 refactor(stm32)!: remove unneeded info from laze context names
  .github/workflows/build-deploy-docs.yml
  .github/workflows/main.yml
  book/src/adding-board-support.md
  doc/support_matrix.yml
  examples/threading-event/laze.yml
  laze-project.yml
  src/ariel-os-stm32-mapping/Cargo.toml
  src/ariel-os-stm32-mapping/build.rs
  src/ariel-os-stm32-mapping/stm32_mapping.csv
  src/ariel-os-stm32/laze.yml
  src/ariel-os-stm32/src/i2c/controller/mod.rs
  src/ariel-os-stm32/src/i2c/mod.rs
  src/ariel-os-stm32/src/lib.rs
  src/ariel-os-stm32/src/spi/main/mod.rs
  src/ariel-os-stm32/src/spi/mod.rs
  src/ariel-os-storage/build.rs
  tests/i2c-controller/src/pins.rs
  tests/spi-loopback/src/pins.rs
  tests/spi-main/src/pins.rs
  tests/threading-lock/laze.yml
  tests/threading-mutex/laze.yml
Labels: build system

#943 feat(boards): add support for the Raspberry Pi Pico 2 W
  doc/support_matrix.yml
  laze-project.yml
  src/ariel-os-rp/src/cyw43.rs
  tests/spi-main/laze.yml
Labels: board, Wi-Fi

#962 feat(stm32c0): complete support for I2C in controller mode
  doc/support_matrix.yml
  src/ariel-os-stm32/src/i2c/controller/mod.rs
  src/ariel-os-stm32/src/i2c/mod.rs
  tests/i2c-controller/laze.yml
  tests/i2c-controller/src/pins.rs
Labels: HAL, chip

#963 feat(stm32c0): complete support for SPI in main mode
  doc/support_matrix.yml
  tests/spi-loopback/src/pins.rs
  tests/spi-main/laze.yml
  tests/spi-main/src/pins.rs
Labels: HAL, chip

#960 refactor(stm32): move the SWI selection to the boards, from the MCUs
  book/src/adding-board-support.md
  laze-project.yml
Labels: build system

#966 docs(porting-guide): drop an extraneous `CONFIG_SWI`
  book/src/adding-board-support.md
Labels: docs

#968 chore(deps): bump to embassy-rp 0.4.0+ariel-os, cyw43-pio 0.4.0
  Cargo.lock
  Cargo.toml
  ariel-os-cargo.toml
  src/ariel-os-rp/Cargo.toml
Labels: HAL

#974 feat(boards): add support for the Nordic Thingy:91 X
  doc/support_matrix.yml
  examples/blinky/laze.yml
  examples/blinky/src/pins.rs
  examples/gpio/laze.yml
  examples/gpio/src/pins.rs
  laze-project.yml
  src/ariel-os-nrf/Cargo.toml
  src/ariel-os-nrf/build.rs
  src/ariel-os-nrf/src/i2c/controller/mod.rs
  src/ariel-os-nrf/src/i2c/mod.rs
  src/ariel-os-nrf/src/identity.rs
  src/ariel-os-nrf/src/lib.rs
  src/ariel-os-nrf/src/spi/main/mod.rs
  src/ariel-os-nrf/src/spi/mod.rs
  src/ariel-os-storage/build.rs
  tests/gpio-interrupt-nrf/src/main.rs
  tests/i2c-controller/laze.yml
  tests/i2c-controller/src/main.rs
  tests/i2c-controller/src/pins.rs
  tests/spi-main/laze.yml
  tests/spi-main/src/main.rs
  tests/spi-main/src/pins.rs
Labels: board, chip

#975 refactor(boards)!: rename `nrf9160dk` to `nrf9160dk-nrf9160`
  doc/support_matrix.yml
  examples/blinky/laze.yml
  examples/blinky/src/pins.rs
  examples/gpio/laze.yml
  examples/gpio/src/pins.rs
  examples/http-server/laze.yml
  examples/http-server/src/pins.rs
  laze-project.yml
  tests/coap-blinky/laze.yml
Labels: board

#976 fix(laze): change order of `root`/`relroot` for Ariel Cargo config
  laze-project.yml
Labels: build system

#477 feat(boards): add initial support for Espressif ESP32-C3-LCDkit
  doc/support_matrix.yml
  laze-project.yml
Labels: board

#983 feat(boards): add support for the FireBeetle 2 ESP32-C6
  examples/blinky/src/pins.rs
  examples/gpio/src/pins.rs
  laze-project.yml
Labels: board

#991 docs(dfrobot-firebeetle2-esp32-c6): fix pin definitions
  examples/blinky/src/pins.rs
  examples/gpio/src/pins.rs
Labels: board

#992 chore(book): remove the unused and deprecated `multilingual` field
  book/book.toml
Labels: cleanup

#994 chore(stm32): enable `has_eth_stm32` for the `st-nucleo-h755zi-q`
  laze-project.yml
Labels: network, board

#999 ci: bump GHA caching actions
  .github/workflows/build.yml
Labels: CI

#998 docs: fix paths to the networking setup instructions
  examples/coap-client/README.md
  examples/coap-server/README.md
  tests/coap-blinky/README.md
  tests/coap/README.md
Labels: docs

#1002 feat(boards): add support for the ST NUCLEO-F411RE
  doc/support_matrix.yml
  examples/blinky/laze.yml
  examples/blinky/src/pins.rs
  examples/gpio/laze.yml
  examples/gpio/src/pins.rs
  laze-project.yml
  src/ariel-os-stm32/src/i2c/controller/mod.rs
  src/ariel-os-stm32/src/i2c/mod.rs
  src/ariel-os-stm32/src/spi/main/mod.rs
  src/ariel-os-stm32/src/spi/mod.rs
  tests/spi-loopback/laze.yml
  tests/spi-loopback/src/pins.rs
Labels: board, chip

#1003 docs: use `Timer::after_millis()` to avoid the need for `Duration`
  examples/blinky/src/main.rs
  examples/gpio/src/main.rs
  examples/power/src/main.rs
  examples/thread-async-interop/src/main.rs
  examples/usb-keyboard/src/main.rs
Labels: docs
