Repository ariel-os/ariel-os, pull requests merged in 2025-01, with the labels that each got.

#650 ci: use laze for `cargo-test`
  .github/workflows/main.yml
  laze-project.yml
  src/ariel-os-embassy-common/Cargo.toml
  src/ariel-os-embassy-common/laze.yml
  src/ariel-os-embassy/Cargo.toml
  src/ariel-os-embassy/laze.yml
  src/ariel-os-identity/Cargo.toml
  src/ariel-os-identity/laze.yml
  src/ariel-os-macros/Cargo.toml
  src/ariel-os-macros/laze.yml
  src/ariel-os-nrf/Cargo.toml
  src/ariel-os-nrf/laze.yml
  src/ariel-os-rp/Cargo.toml
  src/ariel-os-rp/laze.yml
  src/ariel-os-runqueue/Cargo.toml
  src/ariel-os-runqueue/laze.yml
  src/ariel-os-stm32/Cargo.toml
  src/ariel-os-stm32/laze.yml
  src/ariel-os-threads/Cargo.toml
  src/ariel-os-threads/laze.yml
  src/ariel-os/Cargo.toml
  src/ariel-os/laze.yml
  src/laze.yml
  src/lib/coapcore/Cargo.toml
  src/lib/coapcore/laze.yml
  src/lib/laze.yml
  src/lib/rbi/Cargo.toml
  src/lib/rbi/laze.yml
  src/lib/ringbuffer/Cargo.toml
  src/lib/ringbuffer/laze.yml
Labels: testing, build system

#652 docs(log): rename the `log` example to `example-log`
  Cargo.lock
  examples/log/Cargo.toml
  examples/log/laze.yml
Labels: docs

#658 chore(rt): remove an unused `cbindgen` configuration file
  src/ariel-os-rt/cbindgen.toml
Labels: cleanup

#661 refactor(threading)!: rename `*_NUMOF` to `*_COUNT`
  src/ariel-os-threads/src/lib.rs
  src/ariel-os-threads/src/thread.rs
  src/ariel-os-threads/src/thread_flags.rs
Labels: threading

#663 docs(thread): enable the rendering of the `core-affinity` feature
  .github/workflows/build-deploy-docs.yml
  .github/workflows/main.yml
  src/ariel-os-threads/src/smp/mod.rs
Labels: docs, threading

#606 docs(threading-event): Clean up the threading-event example
  examples/threading-event/README.md
  examples/threading-event/src/main.rs
Labels: docs, threading

#670 chore: remove riotboot-related configuration
  doc/build_system.md
  laze-project.yml
Labels: build system

#673 doc: Update hello-world recording
  doc/hello-world_render.svg
  doc/recorder_template.svg
  scripts/recorder.sh
Labels: docs

#504 feat(build): initial Ferrocene support
  book/src/SUMMARY.md
  book/src/tooling/ferrocene.md
  criticalup.toml
  laze-project.yml
Labels: enhancement, build system

#585 feat: Share code with RIOT OS
  Cargo.lock
  Cargo.toml
  deny.toml
  examples/blinky/laze.yml
  examples/blinky/src/pins.rs
  tests/coap-blinky/Cargo.toml
  tests/coap-blinky/README.md
  tests/coap-blinky/laze.yml
  tests/coap-blinky/src/main.rs
  tests/coap/Cargo.toml
  tests/coap/src/main.rs
  tests/laze.yml
Labels: testing

#678 ci(docs): render documentation for network protocols
  .github/workflows/build-deploy-docs.yml
  .github/workflows/main.yml
Labels: docs, CI

#680 chore(threads): delete the outdated README
  src/ariel-os-threads/README.md
Labels: docs, threading

#682 docs(book): remove old manifesto
  book/src/SUMMARY.md
  book/src/manifesto.md
Labels: docs

#687 feat(thread): provide as many priority levels as the max thread count
  src/ariel-os-threads/src/lib.rs
Labels: threading

#689 docs(book): reorganize the developer guide section
  book/src/COC_reporting.md
  book/src/CODE_OF_CONDUCT.md
  book/src/SUMMARY.md
  book/src/appendices.md
Labels: docs

#695 feat(build): add `info-modules` laze target
  laze-project.yml
Labels: build system

#701 ci(chatbot): fix the chatbot message string
  .github/workflows/matrix-bot.yml
Labels: CI

#702 docs(support-matrix): document support for ESP32-S3-WROOM-1
  book/src/support_matrix.html
  doc/support_matrix.yml
Labels: docs

#683 docs(book): intro rewrite
  book/src/introduction.md
Labels: docs

#700 docs: split the re-exports imports
  book/src/coding-conventions.md
  examples/coap-client/src/main.rs
  examples/coap-server/src/main.rs
  examples/http-server/src/main.rs
  examples/tcp-echo/src/main.rs
  examples/udp-echo/src/main.rs
  examples/usb-keyboard/src/main.rs
  examples/usb-serial/src/main.rs
  tests/coap-blinky/src/main.rs
  tests/coap/src/main.rs
Labels: docs

#703 fix(boards): rename the ESP32 boards
  .github/workflows/build.yml
  Cargo.lock
  book/src/support_matrix.html
  doc/support_matrix.yml
  laze-project.yml
  src/ariel-os-boards/Cargo.toml
  src/ariel-os-boards/espressif-esp32-devkitc/Cargo.toml
  src/ariel-os-boards/espressif-esp32-devkitc/src/lib.rs
  src/ariel-os-boards/espressif-esp32-s3-devkitc-1/Cargo.toml
  src/ariel-os-boards/espressif-esp32-s3-devkitc-1/src/lib.rs
  src/ariel-os-boards/src/lib.rs
Labels: board, build system

#699 feat(config): export macros providing var env access
  Cargo.lock
  src/ariel-os-utils/src/env.rs
  src/ariel-os/Cargo.toml
  src/ariel-os/src/lib.rs
Labels: config

#698 docs(book): add chapter about `embedded-test` integration
  book/src/SUMMARY.md
  book/src/testing.md
Labels: docs, testing

#708 docs(examples): increase the ISR stack to avoid HardFaults on RPi Pico W
  examples/tcp-echo/laze.yml
  examples/udp-echo/laze.yml
Labels: docs

#710 chore(deps): bump our embassy-net fork
  Cargo.lock
Labels: enhancement, network

#711 ci: preview docs if they changed in a PR
  .github/workflows/build-deploy-docs.yml
  .github/workflows/preview-docs.yml
Labels: docs, CI

#709 fix(examples): re-enable `examples/thread-async-interop` for esp
  examples/thread-async-interop/laze.yml
Labels: docs, threading

#717 ci: drop unneeded `needs` from preview-docs.yml
  .github/workflows/preview-docs.yml
Labels: bug, CI

#722 ci: align workflow run ids for "Preview docs"
  .github/workflows/build-deploy-docs.yml
  .github/workflows/preview-docs.yml
Labels: bug, CI

#718 feat(config): introduce macros to obtain IP addresses at compile time
  Cargo.lock
  Cargo.toml
  deny.toml
  src/ariel-os-debug/Cargo.toml
  src/ariel-os-utils/Cargo.toml
  src/ariel-os-utils/src/env.rs
  src/ariel-os-utils/src/lib.rs
  src/ariel-os/src/lib.rs
Labels: config

#672 docs(book): document how to add support for a board
  book/src/SUMMARY.md
  book/src/adding_board_support.md
  book/src/build_system.md
  doc/add_board_support.md
Labels: docs, board

#693 feat(coap): add ACE EDHOC profile
  Cargo.lock
  _typos.toml
  ariel-os-cargo.toml
  deny.toml
  src/ariel-os-coap/src/lib.rs
  src/lib/coapcore/Cargo.toml
  src/lib/coapcore/src/ace.rs
  src/lib/coapcore/src/error.rs
  src/lib/coapcore/src/iana.rs
  src/lib/coapcore/src/lib.rs
  src/lib/coapcore/src/scope.rs
  src/lib/coapcore/src/seccfg.rs
  src/lib/coapcore/src/seccontext.rs
Labels: CoAP

#715 feat: improve network configuration
  book/src/networking.md
  examples/README.md
  examples/coap-client/Cargo.toml
  examples/coap-client/src/main.rs
  examples/coap-server/Cargo.toml
  examples/coap-server/src/main.rs
  examples/http-client/Cargo.toml
  examples/http-client/src/main.rs
  examples/http-server/Cargo.toml
  examples/http-server/src/main.rs
  examples/tcp-echo/Cargo.toml
  examples/tcp-echo/src/main.rs
  examples/udp-echo/Cargo.toml
  examples/udp-echo/src/main.rs
  laze-project.yml
  src/ariel-os-embassy/Cargo.toml
  src/ariel-os-embassy/src/net.rs
  src/ariel-os-macros/Cargo.toml
  src/ariel-os-macros/src/config.rs
  src/ariel-os/Cargo.toml
  tests/coap-blinky/Cargo.toml
  tests/coap-blinky/src/main.rs
  tests/coap/Cargo.toml
  tests/coap/src/main.rs
Labels: network, config

#741 docs(book-intro): polish the book introduction
  book/src/introduction.md
Labels: docs

#735 docs(README): add a short security section
  README.md
Labels: docs

#716 docs(support-matrix): print the technical name of boards and chips
  book/src/support_matrix.html
  doc/gen_support_matrix_html.rs
  doc/support_matrix.yml
Labels: docs

#739 docs(book): add "Getting Started" chapter
  README.md
  _typos.toml
  book/src/SUMMARY.md
  book/src/build_system.md
  book/src/debug_logging.md
  book/src/getting_started.md
  book/src/hello-world_render.svg
  book/src/multithreading.md
  book/src/networking.md
  book/src/recorder_template.svg
  scripts/recorder.sh
Labels: docs

#756 ci: don't build on main branch push
  .github/workflows/build.yml
Labels: CI

#758 docs(README): polish the README
  README.md
Labels: docs

#676 docs(storage): Clean up the storage example
  examples/README.md
  examples/storage/README.md
  examples/storage/src/main.rs
Labels: docs

#760 docs(getting-started): reduce the set of build dependencies
  book/src/getting_started.md
Labels: docs, build system

#765 docs(support-matrix): uncenter the support matrix
  book/src/support_matrix.html
  doc/gen_support_matrix_html.rs
Labels: docs
