Repository ariel-os/ariel-os, pull requests merged in 2025-05, with the labels that each got.

#1013 build(laze): add a `cargo-expand` task
  laze-project.yml
Labels: build system

#990 fix(log): add support for `log` on architectures without atomics
  Cargo.lock
  src/ariel-os-debug/Cargo.toml
  src/ariel-os-debug/src/lib.rs
Labels: HAL

#949 refactor(esp): make Clippy pedantic happy
  src/ariel-os-esp/src/gpio.rs
  src/ariel-os-esp/src/i2c/controller/mod.rs
  src/ariel-os-esp/src/lib.rs
  src/ariel-os-esp/src/spi/main/mod.rs
  src/ariel-os-rt/src/lib.rs
Labels: HAL

#1020 fix(stm32): increase eth-stm32 executor stacksize requirement
  laze-project.yml
Labels: network

#1024 build(laze): add `info-boards` task
  laze-project.yml
Labels: build system

#1027 docs(hal): reflect laze name change in ariel-os-hal
  src/ariel-os-hal/src/lib.rs
Labels: docs

#1028 refactor(storage): use `if` in place of `match` with an empty branch
  src/ariel-os-hal/src/dummy/storage.rs
  src/ariel-os-storage/src/lib.rs
Labels: storage

#1030 refactor: remove unused heapless dependencies in some examples and tests
  examples/coap-client/Cargo.toml
  examples/coap-server/Cargo.toml
  examples/http-client/Cargo.toml
  examples/http-server/Cargo.toml
  examples/tcp-echo/Cargo.toml
  examples/udp-echo/Cargo.toml
  tests/coap-blinky/Cargo.toml
  tests/coap/Cargo.toml
Labels: docs

#1031 refactor(rp): make Clippy pedantic happy
  src/ariel-os-rp/src/gpio.rs
  src/ariel-os-rp/src/i2c/controller/mod.rs
  src/ariel-os-rp/src/lib.rs
  src/ariel-os-rp/src/spi/main/mod.rs
Labels: HAL

#1041 feat(build): support "dev" profile
  laze-project.yml
Labels: build system

#1045 feat(stm32): provide stm32 peripheral `cfg` metadata
  Cargo.lock
  src/ariel-os-stm32/Cargo.toml
  src/ariel-os-stm32/build.rs
Labels: HAL

#1046 fix(build): model `xtensa` being `nightly`
  laze-project.yml
Labels: HAL, build system

#1037 feat: make heap requirements configurable
  Cargo.lock
  laze-project.yml
  src/ariel-os-alloc/Cargo.toml
  src/ariel-os-alloc/src/lib.rs
Labels: build system

#1047 fix(stm32): select correct `stm32-metapac` features
  src/ariel-os-stm32/Cargo.toml
Labels: bug, HAL, build system

#988 feat(xtensa): take control of `xtensa` ISR stacksize
  laze-project.yml
  src/ariel-os-rt/build.rs
  src/ariel-os-rt/isr_stack.ld.in
  src/ariel-os-rt/src/lib.rs
Labels: HAL

#1034 feat(boards): add support for ST B-L475E-IOT01A
  doc/support_matrix.yml
  examples/blinky/laze.yml
  examples/blinky/src/pins.rs
  examples/gpio/laze.yml
  examples/gpio/src/pins.rs
  laze-project.yml
  src/ariel-os-stm32/src/i2c/controller/mod.rs
  src/ariel-os-stm32/src/i2c/mod.rs
  src/ariel-os-stm32/src/lib.rs
  src/ariel-os-stm32/src/spi/main/mod.rs
  src/ariel-os-stm32/src/spi/mod.rs
  src/ariel-os-storage/build.rs
  tests/coap-blinky/laze.yml
  tests/i2c-controller/laze.yml
  tests/i2c-controller/src/pins.rs
  tests/spi-loopback/laze.yml
  tests/spi-loopback/src/pins.rs
  tests/spi-main/laze.yml
  tests/spi-main/src/pins.rs
Labels: board, chip

#1048 docs(udp-example): use smaller buffers
  examples/udp-echo/src/main.rs
Labels: docs

#1051 chore(build): drop currently not used `esp-storage` patch
  Cargo.lock
  ariel-os-cargo.toml
Labels: cleanup, build system

#1053 feat(build): introduce `ram-tiny` laze module
  examples/threading-channel/laze.yml
  examples/threading-event/laze.yml
  examples/threading/src/main.rs
  laze-project.yml
  tests/benchmarks/bench_sched_flags/laze.yml
  tests/benchmarks/bench_sched_yield/laze.yml
  tests/threading-dynamic-prios/laze.yml
  tests/threading-lock/laze.yml
  tests/threading-mutex/laze.yml
Labels: build system

#1054 ci(cargo): pass `--locked` to Cargo through `laze build`
  .github/workflows/build.yml
  .github/workflows/main.yml
Labels: CI

#1052 feat(debug)!: drop support for print
  examples/log/src/main.rs
  src/ariel-os-debug-log/src/lib.rs
  src/ariel-os-debug/src/lib.rs
Labels: breaking

#1050 feat: add support stm32f042k6 mcu and nucleo board
  doc/support_matrix.yml
  examples/blinky/laze.yml
  examples/blinky/src/pins.rs
  examples/gpio/laze.yml
  examples/gpio/src/pins.rs
  laze-project.yml
  src/ariel-os-rt/Cargo.toml
  src/ariel-os-stm32/src/gpio.rs
Labels: board, chip

#946 docs: Add DCO requirement to CONTRIBUTING.md
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: docs

#1057 docs(support-matrix): add board support tiers
  .github/workflows/main.yml
  book/cmdrun-check.sh
  book/src/hardware-functionality-support.md
  doc/gen_support_matrix_html.rs
  doc/support_matrix.yml
Labels: docs

#1064 docs(stm32): add STM32WBA55CG to the support matrix
  doc/support_matrix.yml
Labels: docs, board, chip

#1066 docs(nrf): add nRF52-DK in the support matrix
  doc/support_matrix.yml
  examples/blinky/laze.yml
  examples/blinky/src/pins.rs
  examples/gpio/laze.yml
  examples/gpio/src/pins.rs
Labels: docs, board, chip
