Repository ariel-os/ariel-os, pull requests merged in 2025-08, with the labels that each got.

#1209 ci(support-matrix): check the rendering of tier 3 boards
  .github/workflows/main.yml
Labels: CI, ci-build:skip

#1210 fix(esp32s3): complete the list of GPIO pins
  src/ariel-os-esp/src/lib.rs
Labels: board, ci-build:esp

#1205 ci(lint): install `taplo-cli` without relying on `cargo-binstall`
  .github/workflows/main.yml
Labels: CI, ci-build:skip

#1216 fix(clippy): allow the `collapsible_if` lint
  Cargo.toml
Labels: ci-build:skip

#1206 ci(build): fix `check-labels` succeeding on PRs with many commits
  .github/workflows/build.yml
Labels: CI, ci-build:rp

#1224 fix(sensors): enable `defmt` on `ariel-os-sensors` when needed
  src/ariel-os/Cargo.toml
Labels: sensor api, ci-build:skip

#1223 fix(sensors): provide a custom `defmt::Format` impl for `MeasurementUnit`
  src/ariel-os-sensors/src/measurement_unit.rs
Labels: sensor api, ci-build:skip

#1218 docs(book): document the process for creating a release of `ariel-os`
  book/src/development-processes.md
Labels: docs, ci-build:skip

#1240 fix: pin sequential-storage to v4.0.1 to avoid v4.0.2 regression and v4.0.3 MSRV
  src/ariel-os-storage/Cargo.toml
Labels: ci-build:rp

#1241 fix(stm32u083mc): disable networking again to accommodate HTTP examples
  laze-project.yml
Labels: chip, ci-build:stm32

#1248 chore: reconfigure renovate
  .github/renovate.json
Labels: CI, ci-build:skip

#1249 chore: prevent matrix bot from reporting renovate PRs
  .github/workflows/matrix-bot.yml
Labels: CI, ci-build:skip

#1220 refactor(sensors): make appropriate iterators `ExactSizeIterator`s
  src/ariel-os-macros/src/define_count_adjusted_sensor_enums.rs
  src/ariel-os-sensors/src/registry.rs
Labels: sensor api, ci-build:skip
