Repository ariel-os/ariel-os, pull requests merged in 2025-02, with the labels that each got.

#770 feat(net): use an RNG to seed the network stack, when already enabled
  Cargo.lock
  src/ariel-os-embassy/Cargo.toml
  src/ariel-os-embassy/src/lib.rs
  src/ariel-os/Cargo.toml
Labels: network

#789 refactor: move the conflict with threading into `executor-single-thread`
  laze-project.yml
Labels: threading, build system

#790 fix(alloc): reduce esp default heap size
  src/ariel-os-alloc/src/lib.rs
Labels: HAL

#772 feat(stm32): add partial support for persistent storage
  book/src/support_matrix.html
  doc/support_matrix.yml
  laze-project.yml
  src/ariel-os-hal/Cargo.toml
  src/ariel-os-stm32/Cargo.toml
  src/ariel-os-stm32/src/lib.rs
  src/ariel-os-stm32/src/storage.rs
  src/ariel-os-storage/build.rs
  src/ariel-os-storage/src/lib.rs
Labels: HAL, storage

#795 docs(book): build support matrix on the fly
  .github/workflows/build-deploy-docs.yml
  .github/workflows/main.yml
  book/book.toml
  book/cmdrun-check.sh
  book/src/hardware_functionality_support.md
  book/src/support_matrix.html
Labels: docs, enhancement, CI

#752 feat(coapcore): evaluate tokens' lifetime
  src/ariel-os-coap/src/lib.rs
  src/lib/coapcore/src/ace.rs
  src/lib/coapcore/src/generalclaims.rs
  src/lib/coapcore/src/helpers.rs
  src/lib/coapcore/src/lib.rs
  src/lib/coapcore/src/oluru.rs
  src/lib/coapcore/src/scope.rs
  src/lib/coapcore/src/seccfg.rs
  src/lib/coapcore/src/seccontext.rs
  src/lib/coapcore/src/time.rs
Labels: CoAP

#796 fix(debug-console): enable the debug logging facade only with a console
  laze-project.yml
Labels: build system

#801 ci: enable result-cache for more steps
  .github/workflows/build.yml
Labels: CI, cleanup

#808 chore: add -Z emit-stack-sizes and keep them through linking
  laze-project.yml
  src/ariel-os-rt/build.rs
  src/ariel-os-rt/keep-stack-sizes.x
Labels: build system

#805 fix(coap): tune down UDP buffers
  src/ariel-os-coap/src/lib.rs
Labels: CoAP

#794 docs(FAQ): add FAQ.md
  FAQ.md
  README.md
Labels: docs

#803 feat(coap): laze based configuration
  Cargo.lock
  examples/coap-server/laze.yml
  laze-project.yml
  src/ariel-os-coap/Cargo.toml
  src/ariel-os-coap/src/lib.rs
  src/ariel-os/Cargo.toml
  src/lib/coapcore/src/seccfg.rs
  src/lib/coapcore/src/seccontext.rs
  tests/coap-blinky/laze.yml
  tests/coap/README.md
  tests/coap/laze.yml
Labels: config, CoAP

#738 docs(book/coap): update
  book/src/tooling/coap.md
Labels: docs, CoAP

#807 feat(esp32): add untested support for I2C controller and SPI main
  src/ariel-os-esp/src/i2c/controller/mod.rs
  src/ariel-os-esp/src/i2c/mod.rs
  src/ariel-os-esp/src/spi/main/mod.rs
  src/ariel-os-esp/src/spi/mod.rs
Labels: HAL

#723 docs(support-matrix): add an intermediate support level
  doc/support_matrix.yml
Labels: docs

#816 ci: build.yml only limit build if actually building something
  .github/workflows/build.yml
Labels: CI

#435 feat: initial RasPi Pico 2 support
  .github/workflows/build-deploy-docs.yml
  .github/workflows/main.yml
  Cargo.lock
  doc/support_matrix.yml
  examples/blinky/src/pins.rs
  laze-project.yml
  src/ariel-os-boards/Cargo.toml
  src/ariel-os-boards/rpi-pico2/Cargo.toml
  src/ariel-os-boards/rpi-pico2/src/lib.rs
  src/ariel-os-boards/src/lib.rs
  src/ariel-os-chips/rp235x/Cargo.toml
  src/ariel-os-chips/rp235x/build.rs
  src/ariel-os-chips/rp235x/memory.x
  src/ariel-os-chips/rp235x/src/lib.rs
  src/ariel-os-embassy/src/lib.rs
  src/ariel-os-rp/Cargo.toml
  src/ariel-os-rp/laze.yml
  src/ariel-os-rp/src/i2c/mod.rs
  src/ariel-os-rp/src/lib.rs
  src/ariel-os-rp/src/picotool.rs
  src/ariel-os-rp/src/spi/main/mod.rs
  src/ariel-os-rp/src/spi/mod.rs
  src/ariel-os-rt/Cargo.toml
  src/ariel-os-storage/src/lib.rs
  src/ariel-os-threads/Cargo.toml
  src/ariel-os-threads/src/smp/mod.rs
  src/ariel-os-threads/src/smp/rp.rs
  tests/gpio/src/pins.rs
  tests/i2c-controller/laze.yml
  tests/spi-loopback/laze.yml
Labels: HAL, board

#819 ci(lint): lint coapcore docs
  .github/workflows/main.yml
  src/lib/coapcore/src/seccfg.rs
Labels: CI, CoAP

#823 chore(coapcore): update libOSCORE
  Cargo.lock
  src/lib/coapcore/Cargo.toml
Labels: CoAP

#822 feat(storage)!: change ariel init marker in storage
  src/ariel-os-storage/src/lib.rs
Labels: storage

#828 docs: hide the `storage` Cargo feature from users
  src/ariel-os/Cargo.toml
Labels: docs, storage

#777 feat(esp): solve esp XOR wifi for xtensa
  Cargo.lock
  Cargo.toml
  ariel-os-cargo.toml
  doc/support_matrix.yml
  laze-project.yml
  src/ariel-os-embassy-common/Cargo.toml
  src/ariel-os-embassy-common/src/executor_thread.rs
  src/ariel-os-embassy-common/src/lib.rs
  src/ariel-os-embassy/Cargo.toml
  src/ariel-os-embassy/src/lib.rs
  src/ariel-os-esp/Cargo.toml
  src/ariel-os-esp/src/lib.rs
  src/ariel-os-esp/src/preempt.rs
  src/ariel-os-hal/Cargo.toml
Labels: HAL, threading, Wi-Fi

#832 docs: fix broken links on internal items
  src/ariel-os-storage/src/postcard_value.rs
  src/lib/coapcore/src/error.rs
Labels: docs

#817 chore: run espup through laze and document it
  book/src/getting_started.md
  laze-project.yml
Labels: docs, build system

#837 docs(device-metadata-example): use a task instead of a thread
  examples/device-metadata/laze.yml
  examples/device-metadata/src/main.rs
Labels: docs

#776 ci(lint): add basic checking of internal links in PRs
  .github/workflows/main.yml
Labels: CI

#853 feat(build): make use of `workdir` in laze files
  laze-project.yml
Labels: build system

#854 refactor: drop `riot_binary` variable
  laze-project.yml
Labels: cleanup

#849 fix(smt32): correct STM32WBA55CG support
  laze-project.yml
  src/ariel-os-boards/st-nucleo-wba55/Cargo.toml
Labels: HAL, board

#814 feat(coap): support stored security configurations
  Cargo.lock
  _typos.toml
  book/src/tooling/coap.md
  laze-project.yml
  src/ariel-os-coap/Cargo.toml
  src/ariel-os-coap/build.rs
  src/ariel-os-coap/src/lib.rs
  src/ariel-os-coap/src/stored.rs
  src/ariel-os/Cargo.toml
  src/lib/coapcore/Cargo.toml
  src/lib/coapcore/src/ace.rs
  src/lib/coapcore/src/iana.rs
  src/lib/coapcore/src/lib.rs
  src/lib/coapcore/src/sealed.rs
  src/lib/coapcore/src/seccfg.rs
  src/lib/coapcore/src/seccontext.rs
  tests/coap/README.md
  tests/coap/peers.yml
Labels: crypto, CoAP, storage

#869 ci(support-matrix): check the generation exit code
  .github/workflows/main.yml
Labels: CI

#877 refactor(laze): replace `depends` with `selects`
  book/src/adding_board_support.md
  laze-project.yml
Labels: build system

#873 feat(network): seed `embassy_net` from the device ID when no RNG
  Cargo.lock
  src/ariel-os-embassy/Cargo.toml
  src/ariel-os-embassy/src/lib.rs
  src/ariel-os-embassy/src/net.rs
Labels: network
